# Generated by Django 2.2.3 on 2020-12-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekEvent', '0002_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
