# Generated by Django 2.2.3 on 2020-12-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekEvent', '0004_auto_20201231_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
